### ISSUE TITLE
[Bug]: Windows Server 22 Native issue

### ISSUE THREAD

**Issue by mastercho** [openbullet/OpenBullet2#1073]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Abug) *(I've searched it)*.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

```
Unhandled exception thrown on 7/18/2024 2:02:47 PM
System.NotSupportedException: No imaging component suitable to complete this operation was found.
 ---> System.Runtime.InteropServices.COMException (0x88982F8B): The component initialization has failed. (0x88982F8B)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at OpenBullet2.Native.Utils.Images.BytesToBitmapImage(Byte[] bytes)
   at OpenBullet2.Native.Utils.Images.Base64ToBitmapImage(String base64)
   at OpenBullet2.Native.Views.Dialogs.MultiRunJobOptionsViewModel.SetConfigData()
   at OpenBullet2.Native.Views.Dialogs.MultiRunJobOptionsViewModel.SelectConfig(ConfigViewModel vm)
   at OpenBullet2.Native.Views.Dialogs.MultiRunJobOptionsDialog.SelectConfig(ConfigViewModel config)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

For some reason when select config in Native shows this error:
![image](https://github.com/user-attachments/assets/9f6ddca5-1140-4352-9e5b-007065ba573e)

### Reproduction steps

1. Start Openbullet 2 native in windows server 22
2. create job
3. select config

### What is the current bug behavior?

.

### What is the expected correct behavior?

To create job and select config without error

### Version of the client

0.3.1

### Type of client

Native client

### Environment

```markdown
- OS: Windows Server 2022
- Virtualization: Probably KVM as is RDP
- Browser: Chrome 126
```

**Comment by openbullet** [comment]
By googling I found this, maybe the error can safely be ignored https://github.com/microsoft/PowerToys/pull/29663/files

**Comment by openbullet** [comment]
Should be fixed now
