### ISSUE TITLE
[Bug]: Front-end build instructions missing from documentation

### ISSUE THREAD

**Issue by dkchwkch** [openbullet/OpenBullet2#1138]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Abug) *(I've searched it)*.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

The vps installs with the following error:
"20:21:10 WRN] The WebRootPath was not found: /root/OpenBullet2/OpenBullet2.Web/bin/Release/net8.0/publish/wwwroot. Static files may be unavailable.
[20:21:10 INF] Now listening on: http://localhost:5000
[20:21:10 INF] Application started. Press Ctrl+C to shut down.
[20:21:10 INF] Hosting environment: Production
[20:21:10 INF] Content root path: /root/OpenBullet2/OpenBullet2.Web/bin/Release/net8.0/publish
[20:21:12 ERR] Generic exception
System.IO.FileNotFoundException: Could not find file '/root/OpenBullet2/OpenBullet2.Web/bin/Release/net8.0/publish/wwwroot/index.html'.
File name: '/root/OpenBullet2/OpenBullet2.Web/bin/Release/net8.0/publish/wwwroot/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor.GetFileInfo(String path)
   at Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor.ExecuteAsync(ActionContext context, PhysicalFileResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at OpenBullet2.Web.Exceptions.AuthTokenVerificationMiddleware.InvokeAsync(HttpContext context)
   at OpenBullet2.Web.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context)
"

### Reproduction steps

"/root/OpenBullet2/OpenBullet2.Web/bin/Release/net8.0/publish/wwwroot/index.html " Missing documents

### What is the current bug behavior?

"/root/OpenBullet2/OpenBullet2.Web/bin/Release/net8.0/publish/wwwroot/index.html " Missing documents

### What is the expected correct behavior?

"/root/OpenBullet2/OpenBullet2.Web/bin/Release/net8.0/publish/wwwroot/index.html " Documentation exists

### Version of the client

2

### Type of client

Web client

### Environment

```markdown
- OS:Ubuntu 22.04.5
- Virtualization: KVM
- Browser:
```

**Comment by openbullet** [comment]
Hello, if you want to compile the web client on your own, then you also need to build the front-end and add the files to the `wwwroot` directory. I just now realized this is not documented in the [official documentation](https://docs.openbullet.dev/docs/installation/own-build), so I'm going to fix it.

Anyways, these are the steps to do it:
1. Install node version 20
2. Open a terminal in the `openbullet2-web-client` folder of the repository
3. Run `npm install`
4. Run `npm run build`
5. Copy all the files from the `dist` folder to the `wwwroot` folder you mentioned

Now it should work properly.

**Comment by openbullet** [comment]
Done
