### ISSUE TITLE
[BUG] Exception when there are many combinations

### ISSUE THREAD

**Issue by ENORMOUZ** [openbullet/OpenBullet2#115]
**Describe the bug**
When selecting the "Combinations" option in the Job data pool section, the combinations are generated instantly, opposed to dynamically as they are supposed to.

**To Reproduce**
1. Create a Job
2. Go to the Data Pool Section
3. Select "Combinations"
4. Set a combination that has more than euler's number (1.32131....E +) combinaitons
5. Save the Job

**Expected behavior**
The combinations are created dynamically.

However, the conbinations are all generated at once, causing OB2 to crash.

**Comment by openbullet** [comment]
Can you please describe what you mean by "crash"? Do you get the red bar at the bottom of the page telling you to reload? If that's the case, can you please press F12 and send me the content of the exception you see in red in the javascript console? Thanks!

**Comment by ENORMOUZ** [comment]
is it the blazor-error-ui?

**Comment by ENORMOUZ** [comment]
[2021-03-16T15:14:13.846Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenBullet2.Shared.DataPoolSelector.<BuildRenderTree>b__0_28(RenderTreeBuilder __builder3) in D:\a\OpenBullet2\OpenBullet2\OpenBullet2\Shared\DataPoolSelector.razor:line 85
   at Microsoft.AspNetCore.Components.Forms.InputSelect`1.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by ENORMOUZ** [comment]
@openbullet

**Comment by openbullet** [comment]
What you sent is related to wordlist types, not this bug.
Anyways, I fixed the error with huge combinations in https://github.com/openbullet/OpenBullet2/commit/105a4d96e0a96738ad74721c158b420ca9b0e702 (tested and works)
