### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by najort01** [openbullet/OpenBullet2#123]
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not find file 'C:\Users\myuser\AppData\Local\Temp\tmpD28D.tmp'.
      System.IO.FileNotFoundException: Could not find file 'C:\Users\myuser\AppData\Local\Temp\tmpD28D.tmp'.
      File name: 'C:\Users\myuser\AppData\Local\Temp\tmpD28D.tmp'
         at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
         at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
         at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
         at System.IO.StreamReader..ctor(String path, Encoding encoding)
         at System.IO.File.ReadLines(String path)
         at RuriLib.Models.Data.DataPools.FileDataPool..ctor(String fileName, String wordlistType) in D:\a\OpenBullet2\OpenBullet2\RuriLib\Models\Data\DataPools\FileDataPool.cs:line 16
         at OpenBullet2.Services.DataPoolFactoryService.FromOptions(DataPoolOptions options) in D:\a\OpenBullet2\OpenBullet2\OpenBullet2\Services\DataPoolFactoryService.cs:line 30
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '7wRVNdGp6iP33dTEdmpd0MPtCsyd2sykn01dgR2xL_U'.
      System.AggregateException: One or more errors occurred. (Could not find file 'C:\Users\myuser\AppData\Local\Temp\tmpD28D.tmp'.)
       ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\myuser\AppData\Local\Temp\tmpD28D.tmp'.
      File name: 'C:\Users\myuser\AppData\Local\Temp\tmpD28D.tmp'
         at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
         at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
         at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
         at System.IO.StreamReader..ctor(String path, Encoding encoding)
         at System.IO.File.ReadLines(String path)
         at RuriLib.Models.Data.DataPools.FileDataPool..ctor(String fileName, String wordlistType) in D:\a\OpenBullet2\OpenBullet2\RuriLib\Models\Data\DataPools\FileDataPool.cs:line 16
         at OpenBullet2.Services.DataPoolFactoryService.FromOptions(DataPoolOptions options) in D:\a\OpenBullet2\OpenBullet2\OpenBullet2\Services\DataPoolFactoryService.cs:line 30
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
         at System.Threading.Tasks.Task`1.get_Result()
         at OpenBullet2.Services.JobFactoryService.MakeMultiRunJob(MultiRunJobOptions options) in D:\a\OpenBullet2\OpenBullet2\OpenBullet2\Services\JobFactoryService.cs:line 97
         at OpenBullet2.Services.JobFactoryService.FromOptions(Int32 id, Int32 ownerId, JobOptions options) in D:\a\OpenBullet2\OpenBullet2\OpenBullet2\Services\JobFactoryService.cs:line 57
         at OpenBullet2.Services.JobManagerService..ctor(IJobRepository jobRepo, JobFactoryService jobFactory, IRecordRepository recordRepo) in D:\a\OpenBullet2\OpenBullet2\OpenBullet2\Services\JobManagerService.cs:line 26
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass6_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
         at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
         at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by najort01** [comment]
Hey i fixed the issue creating a new .tmp archive in the temp folder

**Comment by carlsmallzz** [comment]
facing the same issue how do i fix pls

**Comment by Stable0** [comment]
Facing same issue how to fix ?
