### ISSUE TITLE
[BUG] Fatal error when clicking change inside job runner

### ISSUE THREAD

**Issue by matsver** [openbullet/OpenBullet2#21]
When clicking change inside of the job runner under the config i get an fatal error.

Setup job
click change

**Desktop (please complete the following information):**
 - OS: Microsoft Windows NT 10.0.18363.0
 - Browser Custom electron build (Chromium i guess)
 - Version 7737.37433]

```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at OpenBullet2.Shared.DataPoolSelector.<BuildRenderTree>b__0_31(RenderTreeBuilder __builder3) in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Shared\DataPoolSelector.razor:line 96
         at Microsoft.AspNetCore.Components.Forms.InputSelect`1.BuildRenderTree(RenderTreeBuilder builder)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '9vye3oA2KqsfY3aXzALj74lHhmivTLvZvlPalKM35VA'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at OpenBullet2.Shared.DataPoolSelector.<BuildRenderTree>b__0_31(RenderTreeBuilder __builder3) in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Shared\DataPoolSelector.razor:line 96
         at Microsoft.AspNetCore.Components.Forms.InputSelect`1.BuildRenderTree(RenderTreeBuilder builder)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
      Object name: 'ApplicationDbContext'.
      System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
      Object name: 'ApplicationDbContext'.
         at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
         at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
         at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
         at OpenBullet2.Repositories.DbRepository`1.GetAll() in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Repositories\DbRepository.cs:line 118
         at OpenBullet2.Shared.ProxySourceSelector.OnInitializedAsync() in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Shared\ProxySourceSelector.razor:line 98
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '9vye3oA2KqsfY3aXzALj74lHhmivTLvZvlPalKM35VA'.
      System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
      Object name: 'ApplicationDbContext'.
         at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
         at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
         at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
         at OpenBullet2.Repositories.DbRepository`1.GetAll() in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Repositories\DbRepository.cs:line 118
         at OpenBullet2.Shared.ProxySourceSelector.OnInitializedAsync() in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Shared\ProxySourceSelector.razor:line 98
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by openbullet** [comment]
This is due to the fact that your Environment.ini was changed with respect to the one you had when creating the job (you removed that wordlist type)
