### ISSUE TITLE
[BUG] Error Upon Cloning a Job with Infinite as Data Pool

### ISSUE THREAD

**Issue by Official-Husko** [openbullet/OpenBullet2#230]
**Describe the bug**
Cloning a job with a data pool set as infinite makes the program break until it is reloaded into a different place then the clone job page.

**To Reproduce**
1. Go to 'Jobs'
2. Click on Clone on a Job that has data pool set to infinite
3. See error

**Expected behavior**
A normal clone window.

**Screenshots**
![(28)](https://user-images.githubusercontent.com/27901510/115117671-17559300-9fa0-11eb-98fb-f1faa1421200.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: Latest

**Error**
```js
[2021-04-17T14:47:43.508Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.

   at OpenBullet2.Shared.DataPoolSelector.<BuildRenderTree>b__0_31(RenderTreeBuilder __builder3) in D:\a\OpenBullet2\OpenBullet2\OpenBullet2\Shared\DataPoolSelector.razor:line 96
   at Microsoft.AspNetCore.Components.Forms.InputSelect`1.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by openbullet** [comment]
Did you perhaps change your Environment.ini file since when you created the original job? Because the exception hints to OB2 searching for a Wordlist Type that is not present anymore.

**Comment by Official-Husko** [comment]
> 
> 
> Did you perhaps change your Environment.ini file since when you created the original job? Because the exception hints to OB2 searching for a Wordlist Type that is not present anymore.

I haven't changed anything in that file. And i tried this on multiple jobs and even made new ones and i always experienced that issue/error.

**Comment by openbullet** [comment]
Sorry I tried again but I cannot reproduce this :(

**Comment by Official-Husko** [comment]
> 
> 
> Sorry I tried again but I cannot reproduce this :(

I could offer to send you the environment file or anything else that might help.

**Comment by openbullet** [comment]
> 
> 
> > Sorry I tried again but I cannot reproduce this :(
> 
> I could offer to send you the environment file or anything else that might help.

Send it to my inbox by mail. You can find the address in the readme of the repo.
