### ISSUE TITLE
[BUG] Memory / RAM Spike

### ISSUE THREAD

**Issue by e393** [openbullet/OpenBullet2#276]
![download](https://user-images.githubusercontent.com/34574971/119311990-c5a7c480-bc3f-11eb-9239-f98752e8b110.png)

**Comment by openbullet** [comment]
1. Which version of OB2 is this
2. What were you doing? 
3. How many jobs? 
4. How many bots?
5. How long has it been running for?
6. Do you have bot log enabled in the settings? It can cause high ram usage
7. Please provide a memory dump according to this issue https://github.com/openbullet/OpenBullet2/issues/149

**Comment by e393** [comment]
1. the latest version 0.1.14
2. nothing
3. 1
4. 200
5. 6 hours
6. nope
7. dont have one

it happns and i get this error:

fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'OpenBullet2.ApplicationDbContext'.
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'OpenBullet2.ApplicationDbContext'.
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'OpenBullet2.ApplicationDbContext'.
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      As of "05/24/2021 14:27:17 +00:00", the heartbeat has been running for "00:00:12.3095509" which is longer than "00:00:01". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      As of "05/24/2021 14:44:28 +00:00", the heartbeat has been running for "00:00:09.8339812" which is longer than "00:00:01". This could be caused by thread pool starvation.

**Comment by openbullet** [comment]
Are you getting plenty of hits? Are you using a database hit output or a file system hit output?
Please, if you can, next time it happens make a dump of the memory and send it to me so I can inspect it, thanks.

**Comment by e393** [comment]
> Are you getting plenty of hits? Are you using a database hit output or a file system hit output?
> Please, if you can, next time it happens make a dump of the memory and send it to me so I can inspect it, thanks.

yes im getting hits for sure, and i have it saving to the DB, i tried making a dump but file is too large or not accepted its a .DMP extension i made it from the task manager while it was freezing

**Comment by openbullet** [comment]
Please disable the "bot logging" options as that heavily consumes RAM. It's supposed to be used just for testing that a config works, not to run it for long periods of time.

**Comment by e393** [comment]
> Please disable the "bot logging" options as that heavily consumes RAM. It's supposed to be used just for testing that a config works, not to run it for long periods of time.

ok thanks ! i disabled it, ill leave it running overnight see what happens

**Comment by e393** [comment]
![download](https://user-images.githubusercontent.com/34574971/119535414-f548f080-bd55-11eb-89e9-f288bb20da68.png)

ok so disabled the log option been running for 10 hrs 200 bots, not consol errors
