### ISSUE TITLE
[BUG] Error in console after running for a while

### ISSUE THREAD

**Issue by e393** [openbullet/OpenBullet2#286]
getting this error in the console after running over night, i dont see any issues but after a while it does crash 

warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Collection was modified; enumeration operation may not execute.
      System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
         at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
         at OpenBullet2.Shared.MultiRunJobViewer.BuildRenderTree(RenderTreeBuilder __builder) in D:\a\OpenBullet2\OpenBullet2\OpenBullet2\Shared\MultiRunJobViewer.razor:line 136
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'FSzI9K9aX0GHXXUW4HikpcrCiAxKPeQIfIZlDlgUiFg'.
      System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
         at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
         at OpenBullet2.Shared.MultiRunJobViewer.BuildRenderTree(RenderTreeBuilder __builder) in D:\a\OpenBullet2\OpenBullet2\OpenBullet2\Shared\MultiRunJobViewer.razor:line 136
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: A task was canceled.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.AspNetCore.Components.Web.Virtualization.VirtualizeJsInterop.DisposeAsync()
         at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List`1 tasks)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'FSzI9K9aX0GHXXUW4HikpcrCiAxKPeQIfIZlDlgUiFg'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.AspNetCore.Components.Web.Virtualization.VirtualizeJsInterop.DisposeAsync()
         at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List`1 tasks)

**Comment by openbullet** [comment]
This will be fixed in the new client
