### ISSUE TITLE
[BUG]System typeload exception when running debugger

### ISSUE THREAD

**Issue by xkeksi** [openbullet/OpenBullet2#303]
**Describe the bug**
If you try to run the debugger on any config, it will "crash"

**To Reproduce**
go to stacker
press debug

**Expected behavior**
kinda obv bruh

**Desktop (please complete the following information):**
 - OS: linux latest
 - Browser: chrome
 - Version: latest

**Additional context**
`Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'ExNqvJhO0sISRsSUuE9O1R7G_3j7IuoeK11qXcgBL7E'.
      System.TypeLoadException: Could not load type 'RuriLib.Models.Data.Resources.Options.ConfigResourceOptions' from assembly 'RuriLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
         at OpenBullet2.Shared.Debugger.Run()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at OpenBullet2.Shared.Debugger.Run()
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
`

**Comment by xkeksi** [comment]
As a side note, this perfectly worked fine until i updated to latest openbullet 2!

**Comment by openbullet** [comment]
The fix for this issue has already been pushed to the repo, I will push update 0.1.16 today so it will be included as this is pretty urgent.
