### ISSUE TITLE
[Bug]: Warn + Fail (Cant identify what it effected)

### ISSUE THREAD

**Issue by JReming85** [openbullet/OpenBullet2#375]
### Version of the software

0.1.21

### Operating system

Microsoft Windows NT 6.2.9200.0 | Server 2012 DC

### Browser

Chrome 91 / Opera 77.0.4054.203

### What happened?

Just saw these 2 in the console log/cmd window

```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100] 
      Unhandled exception rendering component: A task was canceled.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.AspNetCore.Components.Web.Virtualization.VirtualizeJsInterop.DisposeAsync()
         at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List`1 tasks)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'zpxT1XdFg4WuCjs750HhTULjGIoD-7axIbvl280XtpY'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.AspNetCore.Components.Web.Virtualization.VirtualizeJsInterop.DisposeAsync()
         at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List`1 tasks)
```

Looks like there was an eventlog entry for it as well

```
Category: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost
EventId: 111
SpanId: de75614b2895694d
TraceId: aac479f103c14247a99ef5cb2ce5abf3
ParentId: 0000000000000000
ConnectionId: 0HMAH0P10KET3
RequestId: 0HMAH0P10KET3:0000000C
RequestPath: /_blazor/disconnect

Unhandled exception in circuit 'zpxT1XdFg4WuCjs750HhTULjGIoD-7axIbvl280XtpY'.

Exception: 
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Web.Virtualization.VirtualizeJsInterop.DisposeAsync()
   at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List`1 tasks)

```

Not sure if there is any further info I can provide as I do not see any written logs but let me know if there is anything else I can grab for you.

**Comment by openbullet** [comment]
This is just some javascript failing and it's absolutely not a breaking issue. When you read that the error is related to JSINterop, just disregard it. It will not affect your experience in any way, it's just some silly blazor stuff ^_^
