### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chung172000** [openbullet/OpenBullet2#436]
### Version of the software

0.1.22

### Operating system

Windows 11

### Browser / Native

Native

### What happened?

Unhandled exception thrown on 9/8/2021 8:55:11 AM
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Collection was modified; enumeration operation may not execute.)
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityReferenceMap.GetEntriesForState(Boolean added, Boolean modified, Boolean deleted, Boolean unchanged, Boolean hasDependentTypes, Boolean returnAdded, Boolean returnModified, Boolean returnDeleted, Boolean returnUnchanged)+MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManagerExtensions.ToListForState(IStateManager stateManager, Boolean added, Boolean modified, Boolean deleted, Boolean unchanged)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at OpenBullet2.Core.Repositories.DbRepository`1.Update(T entity)
   at OpenBullet2.Core.Repositories.DbProxyRepository.Update(ProxyEntity entity)
   at OpenBullet2.Core.Models.Proxies.DatabaseProxyCheckOutput.Store(Proxy proxy)
   --- End of inner exception stack trace ---

**Comment by openbullet** [comment]
Already fixed in https://github.com/openbullet/OpenBullet2/issues/433 which was a similar issue
