### ISSUE TITLE
[Bug]: Clipboard

### ISSUE THREAD

**Issue by joseminaso** [openbullet/OpenBullet2#469]
### Version of the software

0.1.23

### Operating system

Windows 10 Pro

### Browser / Native

Native

### What happened?

System.Runtime.InteropServices.COMException (0x800401D0): Ошибка при вызове OpenClipboard (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at OpenBullet2.Native.Extensions.IEnumerableExtensions.CopyToClipboard[T](IEnumerable`1 items, Func`2 mapping)
   at OpenBullet2.Native.Views.Pages.MultiRunJobViewer.CopySelectedHits(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by openbullet** [comment]
Is there a particular way to replicate the problem?

**Comment by joseminaso** [comment]
This happens when you copy a good result
