### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Luke20036** [openbullet/OpenBullet2#478]
### Version of the software

OpenBullet2  0.1.24

### Operating system

WIndows10

### Browser / Native

Chrome

### What happened?

fail: Microsoft.EntityFrameworkCore.Update[10000]
An exception occurred in the database while saving changes for context type ‘OpenBullet2.Core.ApplicationDbContext’.
System.InvalidOperationException: The property ‘HitEntity.Id’ has a temporary value while attempting to change the entity’s state to ‘Unchanged’. Either set a permanent value explicitly, or ensure that the database is configured to generate values for this property.
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AcceptChanges()
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.AcceptAllChanges(IReadOnlyList1 changedEntries) at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) System.InvalidOperationException: The property 'HitEntity.Id' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly, or ensure that the database is configured to generate values for this property. at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties) at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AcceptChanges() at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.AcceptAllChanges(IReadOnlyList1 changedEntries)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)…
Hi guys why i have this fail in openbullet2?

**Comment by openbullet** [comment]
Could you provide some more information about what you were doing to make the issue appear and if you can consistently reproduce it (with a step by step description if possible)? Thanks!

**Comment by Luke20036** [comment]
when I start a job on openbullet 2 in the command prompt I get this fail, and I don't know if this affected the results of my job..
