### ISSUE TITLE
[Bug]: Unhandled Exception In webSockets 

### ISSUE THREAD

**Issue by HyperFlaw** [openbullet/OpenBullet2#550]
### Version of the software

0.1.26[Beta]

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

Well Actually! I turned every block in safe mode .. Instead of this i am getting this exception Again n again.. Below are the crash.log

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The remote party closed the WebSocket connection without completing the close handshake.)
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at RuriLib.Blocks.Requests.WebSocket.Methods.<>c.<WsConnect>b__0_2(DisconnectionInfo msg)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 54
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 146
   at Websocket.Client.WebsocketClient.Reconnect(ReconnectionType type, Boolean failFast, Exception causedException)
   at Websocket.Client.WebsocketClient.ReconnectSynchronized(ReconnectionType type, Boolean failFast, Exception causedException)
   --- End of inner exception stack trace --- 

Well ! i can't Figure out How to avoid this.

**Comment by HyperFlaw** [comment]
![photo_2021-11-16_07-57-33](https://user-images.githubusercontent.com/74339566/141884728-8e7969a3-e021-46d8-a11c-b17645ad5c41.jpg)

Here is a Screenshot of The error .. And also this error happens when jobs are running. I haven't got This error in stacker . This error Keeps Popping up.

**Comment by openbullet** [comment]
This is exclusively an issue of the native client, can you confirm that the program does not crash when you click on the Ok button but it continues normally until a new error pops up?

**Comment by openbullet** [comment]
This will be fixed in the next version
