### ISSUE TITLE
[Bug]: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by beyto0o** [openbullet/OpenBullet2#551]
### Version of the software

0.1.26

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

Sometimes i get this error so some of my hits get lost.
I hope it was clear from what I wrote and the picture.

```
[Executing block LoliCode] IndexOutOfRangeException: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at Submission#0.<>c.<Capitalize>b__18_0(String i)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.JoinCore[T](Char* separator, Int32 separatorLength, IEnumerable`1 values)
   at System.String.Join[T](Char separator, IEnumerable`1 values)
   at Submission#0.Capitalize(String word)
   at Submission#0.<<Initialize>>b__0_3(String i)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.ScriptStateTaskExtensions.CastAsync[S,T](Task`1 task)
   at RuriLib.Models.Debugger.ConfigDebugger.Run()


BOT ENDED AFTER 5788 ms WITH STATUS: ERROR
```

![11](https://user-images.githubusercontent.com/90928376/142286706-97897f59-9fa6-4751-9998-8d50b20cde77.jpg)

### Relevant LoliCode if needed

```shell
// C# code where I get the error

string Capitalize(string word)
{
    var split = word.Split(' ');
    var capitalized = split.Select(i => i[0].ToString().ToUpper() + i[1..]);
    return string.Join(' ', capitalized);
}

List = List.Select(i => Capitalize(i)).ToList();
```

**Comment by openbullet** [comment]
This is not an OB2 bug, this is just some C# code that I gave you where I didn't bother to check for possibly empty strings.
Just use this one instead

```cs
string Capitalize(string word)
{
    if (string.IsNullOrWhiteSpace(word))
    {
        return string.Empty;
    }

    var split = word.Split(' ', StringSplitOptions.RemoveEmptyEntries);

    if (split.Length == 0)
    {
        return word;
    }

    var capitalized = split.Select(i =>
    {
        if (i.Length == 1)
        {
            return i.ToUpper();
        }

        return i[0].ToString().ToUpper() + i[1..];
    });

    return string.Join(' ', capitalized);
}

List = List.Select(i => Capitalize(i)).ToList();
```

**Comment by beyto0o** [comment]
teşekkürler
