### ISSUE TITLE
[Bug]: The given key 'httpLibrary' was not present in the dictionary

### ISSUE THREAD

**Issue by thepasto** [openbullet/OpenBullet2#614]
### Version of the software

0.2.0

### Operating system

Archlinuxarm

### Browser / Native

Chrome 97.0.4692.99

### What happened?

Hello, i just updated to 0.2.0 version, i can't create/edit http request block anymore, here's the log.

```
gen 28 18:25:04 alarmpi dotnet[906]: warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
gen 28 18:25:04 alarmpi dotnet[906]:       Unhandled exception rendering component: The given key 'httpLibrary' was not present in the dictionary.
gen 28 18:25:04 alarmpi dotnet[906]:       System.Collections.Generic.KeyNotFoundException: The given key 'httpLibrary' was not present in the dictionary.
gen 28 18:25:04 alarmpi dotnet[906]:          at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
gen 28 18:25:04 alarmpi dotnet[906]:          at OpenBullet2.Shared.HttpRequestBlockSettingsViewer.BuildRenderTree(RenderTreeBuilder __builder)
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, >
gen 28 18:25:04 alarmpi dotnet[906]: fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
gen 28 18:25:04 alarmpi dotnet[906]:       Unhandled exception in circuit 'NW3b0Lgp7jOgtGZQBSlSP0K3jDy48HX3gNgJy9cgBrs'.
gen 28 18:25:04 alarmpi dotnet[906]:       System.Collections.Generic.KeyNotFoundException: The given key 'httpLibrary' was not present in the dictionary.
gen 28 18:25:04 alarmpi dotnet[906]:          at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
gen 28 18:25:04 alarmpi dotnet[906]:          at OpenBullet2.Shared.HttpRequestBlockSettingsViewer.BuildRenderTree(RenderTreeBuilder __builder)
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, >
gen 28 18:25:04 alarmpi dotnet[906]: warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
gen 28 18:25:04 alarmpi dotnet[906]:       Unhandled exception rendering component: Cannot access a disposed object.
gen 28 18:25:04 alarmpi dotnet[906]:       System.ObjectDisposedException: Cannot access a disposed object.
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequenc>
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& di>
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatc>
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, >
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
gen 28 18:25:04 alarmpi dotnet[906]: fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
gen 28 18:25:04 alarmpi dotnet[906]:       Unhandled exception in circuit 'NW3b0Lgp7jOgtGZQBSlSP0K3jDy48HX3gNgJy9cgBrs'.
gen 28 18:25:04 alarmpi dotnet[906]:       System.ObjectDisposedException: Cannot access a disposed object.
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequenc>
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& di>
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatc>
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, >
gen 28 18:25:04 alarmpi dotnet[906]:          at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

```
Thanks for your work and time

**Comment by openbullet** [comment]
Hello, can you try and redownload OB2 from scratch? Does it give the same error?

**Comment by thepasto** [comment]
It seems to work as well, thanks again
