### ISSUE TITLE
[Bug]: Fatal Error

### ISSUE THREAD

**Issue by Bugleman** [openbullet/OpenBullet2#649]
### Version of the software

0.2.0

### Operating system

Linux 5.10.63-v7l+ #1496 SMP

### Browser / Native

Chromium

### What happened?

```
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'OpenBullet2.Core.ApplicationDbContext'.
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

**Comment by JReming85** [comment]
From the sounds of it something you were trying to pass to the db was missing a field

e.g. got a hit with a invalid user/pass (missing one or the other), list your capturing or script your using is trying to go out of bounds, etc.

I would say start with checking the script and go from there.
