### ISSUE TITLE
[Bug]: Clone "Http Request" Error

### ISSUE THREAD

**Issue by Zurzar** [openbullet/OpenBullet2#653]
### Version of the software

0.2.2

### Operating system

Win10

### Browser / Native

Chrome

### What happened?

https://prnt.sc/qsxYMcpDsEpm

When you clone a block, you get an error. Original version release 0.2.2

`Unhandled exception thrown on 12.03.2022 11:35:01
Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type System.Collections.Generic.Dictionary`2+KeyCollection[System.String,System.String]. Path 'Settings.method.FixedSetting.PrettyNames.$values', line 1, position 2265.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(JsonReader reader, JsonArrayContract contract, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
...`

**Comment by openbullet** [comment]
This bug is due to my recent changes to enum parameters so it happens on every block with an enum (a dropdown). I fixed it and I will try to push the new build soon so that there won't be a problem with this anymore.
