### ISSUE TITLE
[Bug]: Unhandled exception thrown on

### ISSUE THREAD

**Issue by cailili126** [openbullet/OpenBullet2#668]
### Version of the software

openbullet2-0.2.3

### Operating system

视窗10

### Browser / Native

native

### What happened?

Unhandled exception thrown on 2022/3/19 16:07:23

### Relevant LoliCode if needed

```shell
System.IO.FileLoadException: Could not load file or assembly 'Markdig, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null'. Application exception (0x80131600)
File name: 'Markdig, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null'
 ---> System.ApplicationException: Assembly Markdig, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null not found
   at RuriLib.Services.PluginRepository.ResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at OpenBullet2.Native.Controls.MarkdownViewer.OnMarkdownTextPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at MS.Internal.Data.PropertyPathWorker.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at OpenBullet2.Native.ViewModels.ViewModelBase.OnPropertyChanged(String propertyName)
   at OpenBullet2.Native.Views.Dialogs.ShowChangelogDialog.ChangelogViewModel.set_Text(String value)
   at OpenBullet2.Native.Views.Dialogs.ShowChangelogDialog.ChangelogViewModel.FetchChangelog()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
```

**Comment by openbullet** [comment]
Please can you download the build again? Sometimes the updater fails to update and does not download some DLL files. It's complaining that it's missing a DLL file.
