### ISSUE TITLE
[Bug]: OpenBullet Issue when opening on macOS Monterey

### ISSUE THREAD

**Issue by thefakedwc** [openbullet/OpenBullet2#670]
### Version of the software

0.2.3

### Operating system

MacOS Monterey

### Browser / Native

Safari 15

### What happened?

Error when opening OpenBullet2.dll file, even though dotnet is updated to the latest and it automatically aborts.

### Relevant LoliCode if needed

```shell
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.Release.json' was not found and is not optional. The expected physical path was '/Users/blank/appsettings.Release.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at OpenBullet2.Program.Main(String[] args)
zsh: abort      dotnet /Users/blank/Downloads/OpenBullet2/OpenBullet2.dll
```

**Comment by meinname** [comment]
You have to cd to the directory where your OpenBullet2.dll is and start it from there
