### ISSUE TITLE
[Bug]: Unhandled exception

### ISSUE THREAD

**Issue by ashelyanim** [openbullet/OpenBullet2#997]
### Version of the software

0.3.0

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

When i Try Open This Sections : Proxies - Edit Config - RL Setting i Get An Error Message (Unhandled exception)

> 
> `Unhandled exception thrown on 7/1/2024 10:39:25 AM
> System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.
>  ---> System.FormatException: DollarSign is not a valid value for PackIconUniconsKind.
>  ---> System.ArgumentException: Requested value 'DollarSign' was not found.
>    at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
>    at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
>    at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
>    at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
>    --- End of inner exception stack trace ---
>    at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
>    at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
>    --- End of inner exception stack trace ---
>    at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
>    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
>    at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
>    at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
>    at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
>    at OpenBullet2.Native.Views.Pages.RLSettings.InitializeComponent()
>    at OpenBullet2.Native.Views.Pages.RLSettings..ctor()
>    at OpenBullet2.Native.MainWindow.NavigateTo(MainWindowPage page)
>    at OpenBullet2.Native.MainWindow.OpenRLSettingsPage(Object sender, MouseEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`
> 
> ### Relevant LoliCode if needed
> 
> _No response_

**Comment by lfak3r** [comment]
I have the same problem. 
I had an issue open, but I closed it because this one opened at the same time

Version of the software
0.3.0

Operating system
Windows 10

Browser / Native
Native

What happened?
Just updated to new version3.0
Neither configuration works.
I have tried to do a clean installation. and create a new configuration.
When creating a new configuration. The same error appears. Cannot be edited.

ERROR:
Unhandled exception
An unhandled exception was thrown, the application Will try to continue running. Please open
the crash.log file, copy the error message inside it and open an issue on the official github
repository. A few details about the exception: Object reference not set to an instance of an
object

Crash.log
Unhandled exception thrown on 01/07/2024 17:53:42
System.Windows.Markup.XamlParseException: Se produjo una excepción al proporcionar un valor en 'System.Windows.Baml2006.TypeConverterMarkupExtension'.
---> System.FormatException: AngleLeft is not a valid value for PackIconUniconsKind.
---> System.ArgumentException: Requested value 'AngleLeft' was not found.
at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result) at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
--- End of inner exception stack trace ---
at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
--- End of inner exception stack trace ---
at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
at OpenBullet2.Native.Views.Pages.Shared.Debugger.InitializeComponent()
at OpenBullet2.Native.Views.Pages.Shared.Debugger..ctor()
at OpenBullet2.Native.Views.Pages.ConfigEditor..ctor()
at OpenBullet2.Native.MainWindow.NavigateTo(MainWindowPage page)
at OpenBullet2.Native.Views.Pages.Configs.NavigateToConfigSection()
at OpenBullet2.Native.Views.Pages.Configs.EditConfig()
at OpenBullet2.Native.Views.Pages.Configs.ListItemDoubleClick(Object sender, MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by openbullet** [comment]
I'm investigating, it seems to be due to some updated nuget packages, maybe `MahApps.Metro.IconPacks`. Somehow we didn't catch it during testing (we mostly focused on the web client). I'll fix it and publish a new version.
